// Package dbtest is the entry gate for the two package-wide database test
// suites: internal/handler and cmd/server.
//
// Why it exists. Both suites used to fall back to a hard-coded
// postgres://multica:multica@localhost:5432/multica when DATABASE_URL was
// unset, and to exit 0 when that database could not be reached. Two failures
// followed from one design:
//
//   - A green package that ran nothing. `ok ... 0.015s` with no tests executed
//     is indistinguishable from a passing suite in every summary that matters,
//     and it was mistaken for one repeatedly.
//   - Connections to whatever happened to be listening on the developer's
//     machine. On 2026-09-19 a test run reached a developer database six
//     times.
//
// The fix is fail-closed: there is no default, no fallback, and no skip. A
// suite that is not explicitly configured for an isolated database exits
// nonzero before it opens a socket.
//
// What this package is NOT. None of the checks here are proof of isolation.
// An environment variable, a database name prefix, a loopback address and a
// marker row are all forgeable by anyone who can set them. They stop ordinary
// misconfiguration - an unset variable, a stale shell, a copied command line -
// from reaching a database that matters. The isolation boundary is the CI
// provisioner that creates a fresh least-privilege role and database per run;
// this package only refuses to run when the process cannot demonstrate it is
// pointed at one.
//
// Contract: docs/development/testing-database-suites.md
package dbtest

import (
	"context"
	"errors"
	"fmt"
	"net/url"
	"os"
	"regexp"
	"strings"

	"github.com/jackc/pgx/v5/pgxpool"
)

// ExitConfig is the status a suite exits with when its configuration is
// missing, malformed or inconsistent. Distinct from 1 so a wrapper can tell a
// refused entry apart from a failing test.
const ExitConfig = 2

// The suites. Each TestMain passes its own constant, and the environment has
// to agree: a handler command that inherited a cmd-server environment is a
// mistake worth catching, not a detail to tolerate.
const (
	SuiteHandler   = "handler"
	SuiteCmdServer = "cmd-server"
)

// Environment variables. All of them are required, and none of them is the
// generic DATABASE_URL: reading that would turn every ordinary development
// shell into an implicit opt-in, which is the whole problem.
const (
	EnvEnabled     = "LORETIDE_DB_TESTS"
	EnvDatabaseURL = "LORETIDE_DB_TEST_DATABASE_URL"
	EnvDatabase    = "LORETIDE_DB_TEST_DATABASE"
	EnvRole        = "LORETIDE_DB_TEST_ROLE"
	EnvRunID       = "LORETIDE_DB_TEST_RUN_ID"
	EnvSuite       = "LORETIDE_DB_TEST_SUITE"
)

// Config is the validated environment. It holds the URL, so it is never
// printed: see Error, which reports the fields that are safe to name.
type Config struct {
	DatabaseURL string
	Database    string
	Role        string
	RunID       string
	Suite       string
}

// Describe names the target without revealing how to reach it. Every
// diagnostic in this package goes through it, so a credential cannot leak
// through an error message written later by someone in a hurry.
func (c Config) Describe() string {
	return fmt.Sprintf("suite=%s database=%s role=%s run=%s", c.Suite, c.Database, c.Role, c.RunID)
}

var (
	// ErrNotEnabled is the common case: somebody ran `go test ./...`. It is not
	// a failure of theirs, but it is still a nonzero exit, because the
	// alternative - skipping - is what hid the problem for months.
	ErrNotEnabled = errors.New(EnvEnabled + "=1 is required: these suites need an isolated database and never choose one for you")
	// ErrIncomplete is a missing or blank required variable.
	ErrIncomplete = errors.New("incomplete database test configuration")
	// ErrSuiteMismatch is an environment built for the other suite.
	ErrSuiteMismatch = errors.New("the configured suite does not match the suite being run")
	// ErrUnsafeURL is a URL that could route somewhere other than the database
	// the caller said it was targeting.
	ErrUnsafeURL = errors.New("the database URL is not acceptable for a test target")
	// ErrIdentityMismatch is a live connection that is not what was promised.
	ErrIdentityMismatch = errors.New("the connected database identity does not match the configured target")
)

// identifierPattern is what a PostgreSQL database or role name may look like
// here. Deliberately narrower than PostgreSQL's own rules: these names are
// generated by CI, and anything needing a quote is a sign something is being
// injected rather than derived.
var identifierPattern = regexp.MustCompile(`^[a-z_][a-z0-9_]{0,62}$`)

// runIDPattern accepts the CI run identity and a hand-made local one, while
// refusing anything that could travel into a name or a log line unexpectedly.
var runIDPattern = regexp.MustCompile(`^[A-Za-z0-9][A-Za-z0-9_.-]{0,63}$`)

// routingKeys are libpq parameters that change WHICH server or database is
// reached. A URL carrying one of them can point somewhere other than the
// database whose name the caller just told us to expect, which would make the
// whole comparison theatre.
var routingKeys = map[string]bool{
	"host": true, "hostaddr": true, "port": true, "user": true,
	"dbname": true, "database": true, "service": true, "servicefile": true,
	"target_session_attrs": true,
}

// allowedQueryKeys are the parameters a test URL may carry. An unrecognised
// key is refused rather than ignored: the list of things libpq understands is
// long and grows, and a key nobody here has considered is exactly the kind of
// thing that turns out to matter.
var allowedQueryKeys = map[string]bool{
	"sslmode": true, "connect_timeout": true, "application_name": true,
	"sslrootcert": true, "sslcert": true, "sslkey": true,
	"pool_max_conns": true, "pool_min_conns": true,
}

// LoadRequired reads and validates the environment. It performs no I/O, so it
// is fully unit tested, and it runs BEFORE any pool is created: a refused
// configuration must never open a socket.
func LoadRequired(expectedSuite string) (Config, error) {
	if os.Getenv(EnvEnabled) != "1" {
		return Config{}, ErrNotEnabled
	}

	cfg := Config{
		DatabaseURL: strings.TrimSpace(os.Getenv(EnvDatabaseURL)),
		Database:    strings.TrimSpace(os.Getenv(EnvDatabase)),
		Role:        strings.TrimSpace(os.Getenv(EnvRole)),
		RunID:       strings.TrimSpace(os.Getenv(EnvRunID)),
		Suite:       strings.TrimSpace(os.Getenv(EnvSuite)),
	}

	for name, value := range map[string]string{
		EnvDatabaseURL: cfg.DatabaseURL,
		EnvDatabase:    cfg.Database,
		EnvRole:        cfg.Role,
		EnvRunID:       cfg.RunID,
		EnvSuite:       cfg.Suite,
	} {
		if value == "" {
			return Config{}, fmt.Errorf("%w: %s is empty", ErrIncomplete, name)
		}
	}

	if expectedSuite != SuiteHandler && expectedSuite != SuiteCmdServer {
		return Config{}, fmt.Errorf("%w: the code asked for an unknown suite %q", ErrSuiteMismatch, expectedSuite)
	}
	if cfg.Suite != expectedSuite {
		return Config{}, fmt.Errorf("%w: %s=%s but this binary is the %s suite",
			ErrSuiteMismatch, EnvSuite, cfg.Suite, expectedSuite)
	}

	if !identifierPattern.MatchString(cfg.Database) {
		return Config{}, fmt.Errorf("%w: %s is not a plain lowercase identifier", ErrIncomplete, EnvDatabase)
	}
	if !identifierPattern.MatchString(cfg.Role) {
		return Config{}, fmt.Errorf("%w: %s is not a plain lowercase identifier", ErrIncomplete, EnvRole)
	}
	if !runIDPattern.MatchString(cfg.RunID) {
		return Config{}, fmt.Errorf("%w: %s is not an acceptable run identifier", ErrIncomplete, EnvRunID)
	}

	if err := checkURL(cfg.DatabaseURL); err != nil {
		return Config{}, err
	}
	return cfg, nil
}

// checkURL refuses a URL that could reach somewhere other than the single
// named database on the named host.
//
// The URL itself is never quoted back in an error: it carries a password.
func checkURL(raw string) error {
	parsed, err := url.Parse(raw)
	if err != nil {
		// The parser error can echo the input, so it is deliberately dropped.
		return fmt.Errorf("%w: it is not a parseable URL", ErrUnsafeURL)
	}
	switch parsed.Scheme {
	case "postgres", "postgresql":
	default:
		return fmt.Errorf("%w: scheme %q is not a PostgreSQL URL", ErrUnsafeURL, parsed.Scheme)
	}

	// A host list means pgx may pick a server this check never examined, so
	// the identity comparison would be against the wrong one.
	if strings.Contains(parsed.Host, ",") {
		return fmt.Errorf("%w: multiple hosts are not accepted", ErrUnsafeURL)
	}
	// An empty host is a Unix socket. The provisioner may use one as its
	// privileged admin transport; the test role's URL stays explicit, because
	// a socket path is a filesystem decision this check cannot evaluate.
	if parsed.Hostname() == "" {
		return fmt.Errorf("%w: a host is required; Unix sockets are not accepted", ErrUnsafeURL)
	}
	// A percent-encoded absolute path smuggled into the host is the other way
	// to reach a socket.
	if strings.HasPrefix(parsed.Hostname(), "/") {
		return fmt.Errorf("%w: a socket path is not an acceptable host", ErrUnsafeURL)
	}
	if strings.Trim(parsed.Path, "/") == "" {
		return fmt.Errorf("%w: the URL names no database", ErrUnsafeURL)
	}
	if strings.Contains(strings.Trim(parsed.Path, "/"), "/") {
		return fmt.Errorf("%w: the URL path names more than one database", ErrUnsafeURL)
	}

	query, err := url.ParseQuery(parsed.RawQuery)
	if err != nil {
		return fmt.Errorf("%w: its query string is not parseable", ErrUnsafeURL)
	}
	for key := range query {
		lowered := strings.ToLower(key)
		if routingKeys[lowered] {
			return fmt.Errorf("%w: the query parameter %q can change which server or database is reached", ErrUnsafeURL, lowered)
		}
		if !allowedQueryKeys[lowered] {
			return fmt.Errorf("%w: the query parameter %q has not been reviewed for this contract", ErrUnsafeURL, lowered)
		}
	}
	return nil
}

// liveIdentity is what the server says about the connection, as opposed to
// what the URL claims.
type liveIdentity struct {
	Database     string
	Role         string
	CanLogin     bool
	Super        bool
	CreateDB     bool
	CreateRole   bool
	Replication  bool
	BypassRLS    bool
	OwnsDatabase bool
}

// VerifyConnected compares the live connection against the configuration.
//
// It asks the server rather than trusting the URL: a URL can say anything, and
// what matters is which database answered. The role attributes are checked
// because a suite that can create databases or bypass row security is not the
// least-privilege role CI was asked to provision, whatever it is called.
//
// The owner check shows the role owns THIS database. It does not show the role
// owns nothing else, and this function claims no more than that.
func VerifyConnected(ctx context.Context, pool *pgxpool.Pool, cfg Config) error {
	var live liveIdentity
	err := pool.QueryRow(ctx, `
SELECT current_database(),
       current_user,
       r.rolcanlogin,
       r.rolsuper,
       r.rolcreatedb,
       r.rolcreaterole,
       r.rolreplication,
       r.rolbypassrls,
       (d.datdba = r.oid)
  FROM pg_roles r
  JOIN pg_database d ON d.datname = current_database()
 WHERE r.rolname = current_user`).Scan(
		&live.Database, &live.Role, &live.CanLogin, &live.Super, &live.CreateDB,
		&live.CreateRole, &live.Replication, &live.BypassRLS, &live.OwnsDatabase)
	if err != nil {
		return fmt.Errorf("%w: could not read the connected identity (%s)", ErrIdentityMismatch, cfg.Describe())
	}

	if live.Database != cfg.Database {
		return fmt.Errorf("%w: connected to database %q, expected %q", ErrIdentityMismatch, live.Database, cfg.Database)
	}
	if live.Role != cfg.Role {
		return fmt.Errorf("%w: connected as role %q, expected %q", ErrIdentityMismatch, live.Role, cfg.Role)
	}
	if !live.CanLogin {
		return fmt.Errorf("%w: the connected role cannot log in, which should be impossible", ErrIdentityMismatch)
	}
	for name, held := range map[string]bool{
		"rolsuper":       live.Super,
		"rolcreatedb":    live.CreateDB,
		"rolcreaterole":  live.CreateRole,
		"rolreplication": live.Replication,
		"rolbypassrls":   live.BypassRLS,
	} {
		if held {
			return fmt.Errorf("%w: the connected role holds %s; a test role must hold none of the privileged attributes (%s)",
				ErrIdentityMismatch, name, cfg.Describe())
		}
	}
	if !live.OwnsDatabase {
		return fmt.Errorf("%w: the connected role does not own %q (%s)", ErrIdentityMismatch, live.Database, cfg.Describe())
	}
	return nil
}
